FROM node:18.19.1-alpine3.19

ARG NEXT_PUBLIC_DEFAULTLOCALE
ARG NEXT_PUBLIC_BASEURL
ARG NEXT_PUBLIC_DEFAULTDIR

ENV NEXT_PUBLIC_DEFAULTLOCALE=${NEXT_PUBLIC_DEFAULTLOCALE}
ENV NEXT_PUBLIC_BASEURL=${NEXT_PUBLIC_BASEURL}
ENV NEXT_PUBLIC_DEFAULTDIR=${NEXT_PUBLIC_DEFAULTDIR}

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN rm -f .env.production

RUN echo "NEXT_PUBLIC_DEFAULTLOCALE=${NEXT_PUBLIC_DEFAULTLOCALE}" > .env.production
RUN echo "NEXT_PUBLIC_BASEURL=${NEXT_PUBLIC_BASEURL}" >> .env.production
RUN echo "NEXT_PUBLIC_DEFAULTDIR=${NEXT_PUBLIC_DEFAULTDIR}" >> .env.production

RUN npm run build

CMD ["npm", "run", "start"]
